package rediscluster

// slotCount is the fixed number of hash slots in a Redis Cluster.
const slotCount = 16384

// crc16tab is the canonical Redis CRC16 table (CCITT/XMODEM, poly 0x1021, init 0).
// It is generated by initCRC16Table from the polynomial; the values below are the
// well-known Redis crc16tab and MUST NOT be edited — they make CLUSTER KEYSLOT
// match real Redis byte-for-byte.
var crc16tab [256]uint16

func init() {
	const poly = 0x1021
	for i := 0; i < 256; i++ {
		crc := uint16(i) << 8
		for j := 0; j < 8; j++ {
			if crc&0x8000 != 0 {
				crc = (crc << 1) ^ poly
			} else {
				crc <<= 1
			}
		}
		crc16tab[i] = crc
	}
}

// crc16 computes the CCITT/XMODEM CRC16 of buf (init 0), matching Redis crc16.c.
func crc16(buf []byte) uint16 {
	var crc uint16
	for _, b := range buf {
		crc = (crc << 8) ^ crc16tab[byte(crc>>8)^b]
	}
	return crc
}

// hashTag returns the slice of key that should be hashed: if key contains a "{"
// followed by a "}" with at least one byte between them, only that inner span is
// hashed; otherwise the whole key is hashed. Mirrors Redis keyHashSlot().
func hashTag(key []byte) []byte {
	open := -1
	for i := 0; i < len(key); i++ {
		if key[i] == '{' {
			open = i
			break
		}
	}
	if open < 0 {
		return key
	}
	for j := open + 1; j < len(key); j++ {
		if key[j] == '}' {
			if j == open+1 { // "{}" empty tag -> hash whole key
				return key
			}
			return key[open+1 : j]
		}
	}
	return key // "{" with no matching "}" -> hash whole key
}

// Key2Slot maps a key to its hash slot in [0, 16384).
func Key2Slot(key string) uint16 {
	return crc16(hashTag([]byte(key))) % slotCount
}
